# fly.toml app configuration file generated for uci-housing on 2024-08-28T22:44:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uci-housing'
primary_region = 'lax'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
